name: KukuPad CI

on:
  push:
    branches-ignore:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup node.jobs
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: install package
        run: yarn

      - name: eslint
        run: yarn lint
