name: KukuPad CI

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup node.jobs
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: install package
        run: yarn

      - name: eslint
        run: yarn lint

  deploy:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup node.jobs
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: install package
        run: yarn

      - name: build
        run: yarn build

      - name: deploy
        run: yarn deploy
