name: KukuPad CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: setup node.jobs
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - uses: actions/checkout@v2

      - name: setup git
        run: |
          git config user.email "masayuki144@gmail.com"
          git config user.name "Masayuki Morisaki"

      - name: install package
        run: yarn

      - name: build
        run: yarn build

      - name: deploy
        run: npx gh-pages -d build
