name: KukuPad CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup node.jobs
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: copy ssh key
        run: |
          echo "$PRIVATE_KEY" > ~/.ssh/github_rsa
          chmod 600 ~/.ssh/github_rsa
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: setup git
        run: |
          git config --global user.email "masayuki144@gmail.com"
          git config --global user.name "Masayuki Morisaki"
          cat <<-EOF
            Host github.com
              User git
              HostName github.com
              IdentityFile ~/.ssh/github_rsa
          EOF

      - name: install package
        run: yarn

      - name: build
        run: yarn build

      - name: deploy
        run: yarn deploy
