name: KukuPad CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: stefanzweifel/git-auto-commit-action@v4

      - name: setup node.jobs
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: install package
        run: yarn

      - name: build
        run: yarn build

      - name: deploy
        run: yarn deploy
